@startuml classsample
title: 情報システム設計最終課題

class User {
    int id
    String name
    String pass
    String created_at
    String updated_at
}
class  Result{
    int id
    int round
    Date date
    int Match_id
    int score_id_1
    int score_id_2
}
class Match{
    int id
    String name
}
class Score{
    int id
    int score
    int user_id
    int result_id
}
User "1..*" -- "1" Match
User "2" -- "0..*" Result
Match "1" -- "1..*" Result
Score "2" -- "1" Result

@enduml